import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faEllipsisV,
  faUserPlus,
  faEdit,
  faBan,
  faEnvelope,
  faTimes,
  faSave,
  faPencilAlt,
  faInfo,
  faPlus,
  faTrash,
  faKey,
  faArrowRight,
  faArrowLeft,
  faTrashAlt,
  faCheck,
  faPaperPlane,
  faIdBadge,
  faUserEdit,
  faArchive,
  faUserCheck,
  faUserSlash,
  faUserTimes,
  faPhone,
  faUser,
  faToggleOn,
  faDesktop,
  faMobileAlt,
  faTabletAlt,
  faExpandAlt,
  faCompressAlt,
  faHome,
  faThLarge,
  faUsers,
  faUserTag,
  faListAlt,
  faBuilding,
  faSignOutAlt,
  faBars,
  faSearch,
  faQuestion,
  faCog,
  faSms,
  faChevronRight,
  faBriefcase,
  faMinusCircle,
  faGhost,
  faCoffee,
  faGlobe,
  faUserClock,
  faChevronDown,
  faEllipsisH,
  faFont,
  faMoon,
  faSun
} from '@fortawesome/free-solid-svg-icons';
import { faFontAwesomeFlag, faFacebookSquare, faTwitterSquare, faInstagram } from '@fortawesome/free-brands-svg-icons';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';

@NgModule({
  imports: [CommonModule, FontAwesomeModule],
  exports: [FontAwesomeModule]
})
export class IconModule {
  constructor(library: FaIconLibrary) {
    library.addIcons(
      faEllipsisV,
      faUserPlus,
      faEdit,
      faBan,
      faEnvelope,
      faTimes,
      faSave,
      faPencilAlt,
      faInfo,
      faPlus,
      faTrash,
      faKey,
      faArrowRight,
      faArrowLeft,
      faTrashAlt,
      faCheck,
      faPaperPlane,
      // user icons need to preload for dialog...todo check
      faIdBadge,
      faUserEdit,
      faArchive,
      faUserCheck,
      faUserSlash,
      faUserTimes,
      faPhone,
      faFontAwesomeFlag,
      faCompressAlt,
      faExpandAlt,
      faUser,
      faToggleOn,
      faDesktop,
      faTabletAlt,
      faMobileAlt,
      faFacebookSquare,
      faTwitterSquare,
      faInstagram,
      faHome,
      faThLarge,
      faUser,
      faUsers,
      faUserTag,
      faListAlt,
      faBuilding,
      faSignOutAlt,
      faBars,
      faArrowLeft,
      faSearch,
      faQuestion,
      faCog,
      faTimes,
      faSms,
      faChevronRight,
      faSignOutAlt,
      faBriefcase,
      faMinusCircle,
      faGhost,
      faCoffee,
      faGlobe,
      faUserClock,
      faChevronDown,
      faEllipsisH,
      faFont,
      faMoon,
      faSun
    );
  }
}
