export enum SORT_DIRECTION {
  ASC = 'asc',
  DESC = 'desc',
  NONE = ''
}

export enum COLUMN_KEYS {
  ACTIONS = 'actions',
  ADD = 'add',
  AVATAR = 'avatar',
  CREATED_AT = 'created_at',
  CREATOR = 'creator',
  DEADLINE = 'deadline',
  DELETE = 'delete',
  DEPARTMENT = 'department',
  EDIT = 'edit',
  EMAIL = 'email',
  ICON = 'icon',
  ID = 'id',
  KEY = 'key',
  LOGIN = 'login',
  MANAGER = 'manager',
  NAME = 'name',
  PARTICIPANTS = 'participants',
  PHONE = 'phone',
  PRIVILEGES = 'privileges',
  SELECT = 'select',
  SEQUENCE = 'sequence',
  STAGE = 'stage',
  STATE = 'state',
  SURNAME = 'surname',
  TITLE = 'title',
  TYPE = 'type',
  UPDATED_AT = 'updated_at',
  USERS = 'users',
  VIEW = 'view',
  WORKERS = 'workers'
}

export enum COLUMN_LABELS {
  ACTIONS = '',
  ADD = 'Add',
  AVATAR = 'Avatar',
  CREATED_AT = 'Created At',
  CREATOR = 'Creator',
  DEADLINE = 'Deadline',
  DELETE = 'Delete',
  DEPARTMENT = 'Department',
  EDIT = 'Edit',
  EMAIL = 'Email',
  ICON = 'Icon',
  ID = 'Id',
  KEY = 'Key',
  LOGIN = 'Login',
  MANAGER = 'Manager',
  NAME = 'Name',
  PARTICIPANTS = 'Participants',
  PHONE = 'Phone',
  PRIVILEGES = 'Privileges',
  SELECT = 'Select',
  SEQUENCE = '#',
  STAGE = 'Stage',
  STATE = 'State',
  SURNAME = 'Surname',
  TITLE = 'Title',
  TYPE = 'Type',
  UPDATED_AT = 'Updated At',
  USERS = 'Users',
  VIEW = 'View',
  WORKERS = 'Workers'
}
