export enum WhereOperators {
  EQUAL = 'eq',
  NOT_EQUAL = 'ne',
  IS = 'is',
  NOT = 'not',
  OR = 'or',
  GREATER = 'gt',
  GREATER_OR_EQUAL = 'gte',
  LESS = 'lt',
  LESS_OR_EQUAL = 'lte',
  BETWEEN = 'between',
  NOT_BETWEEN = 'notBetween',
  IN = 'in',
  NOT_IN = 'notIn',
  LIKE = 'like',
  NOT_LIKE = 'notLike',
  STARTS_WITH = 'startsWith',
  ENDS_WITH = 'endsWith',
  SUBSTRING = 'substring',
  ILIKE = 'iLike',
  NOT_ILIKE = 'notILike',
  ANY = 'any'
}
